### ISSUE TITLE
Snapcraft Master/Daily builds

### ISSUE THREAD

**Issue by felicianotech** [strawberryssg/strawberry-v0#44]
Enable snaps to publish on a regular basis for non-stable releases. This could be:

- whenever master is built (might be often)
- daily
- some other schedule

They also have a release candidate channel, if that's something we wanted to do.

**Comment by felicianotech** [comment]
I still want to do this however I don't believe this should dumbly push a new release every day. With the size of this project, there's many days where there are no changes at all and these daily releases would be useless.

I'm thinking a daily CircleCI Scheduled Workflow should be put in place. It would have a unique/tiny job that runs first and uses git to determine if there's been any changes. If there hasn't, it would simply fail the job, ending execution right there. If there's changes, it would run the linux tests job followed by the snap release job.

**Comment by felicianotech** [comment]
@chayev Any thoughts on how this might work? On how Brew could be incorporated?

**Comment by FelicianoTech** [comment]
Snap support has been dropped.
